#!/bin/sh
# Xcode Cloud runs this automatically after cloning, before resolving/building.
# The .xcodeproj is generated by XcodeGen (gitignored), so create it here.
set -e

# Install XcodeGen (Homebrew is available on Xcode Cloud runners).
which xcodegen >/dev/null 2>&1 || brew install xcodegen

cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate
