import Foundation

/// Composes the displayed summary string from structured FM output.
/// One source of truth for the "TL;DR + bullets" shape (DRY); generated by the model as
/// separate fields, formatted here so the bullet list is guaranteed, not left to free-form text.
public enum ItemSummary {

    public static func format(tldr: String, keyPoints: [String]) -> String {
        let head = tldr.trimmingCharacters(in: .whitespacesAndNewlines)
        let bullets = keyPoints
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .map { "• \($0)" }

        var blocks: [String] = []
        if !head.isEmpty { blocks.append("TL;DR: \(head)") }
        if !bullets.isEmpty { blocks.append(bullets.joined(separator: "\n")) }
        return blocks.joined(separator: "\n\n")
    }
}
